global using System.Reflection;
global using System.Text.Json;
global using Basket.ApiClients;
global using Basket.Endpoints;
global using Basket.Models;
global using Basket.Services;
global using Catalog.Models;
global using Microsoft.Extensions.Caching.Distributed;
global using ServiceDefaults.Messaging;