global using Catalog.Data;
global using Catalog.Endpoints;
global using Catalog.Models;
global using Catalog.Services;
global using MassTransit;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.AI;
global using ServiceDefaults.Messaging;
global using System.Reflection;